export const PROJECT_LIST = [
  "Zip Pouch","Dr.Naveen Chandra Reddy", "Ravi Hospitals", "GA Digital Solutions", "Tooth Matters", 
  "Training & Discussion", "GA Consulting", "JDP & Co.,", "Internal Review Meetings", 
  "Business Management System Design", "Business Development", "Suraksha Builders", 
  "Sreekanth and Co.,", "Leave", "Holiday", "Corp Team", "Lakhani & Co.,", "Kakatiya Media House", 
  "GA Connect", "Statutory Filings", "Book keeping", "Network", "Sri French Academy", 
  "Timesheet Update", "GA Connect - AMS", "Brain to Spine", "Others", "Clear Skin", 
  "BSR Hospitals", "GA CRM", "Palod & Loya, Chartered Accountants", 
  "Harshavardhan - My lunch box", "Kangan Water Systems", "Great to Trade", "Our Place", 
  "KYPRO", "GA Capital", "GA Properties", "GA BOT", "Easy Credit India", "Powerail", 
  "IT Monk", "The Land Bank", "AI CloudVerse", "Sri Karaaya", "Opendemat", "Daily Huddle", 
  "Kigo Dental", "New Connex", "Padmaja Herbs & Foods", "Aceexcel", "SIPS", 
  "Advocate Naveen Kumar", "KRM Tek", "GA Learning Hub", "TekRPO", "GA ORG SYNC", 
  "IT Breakdown", "Robotouch", "SEO - Others - Maintenance", "SEO - Research", 
  "Content - Research Special Days", "Work Planning & Scheduling", "GAC-Robotouch", 
  "GAC-Sarv Foods", "GAC-Boss Towers", "GAC-Srinivas Farms", "GAC-Training", 
  "Daily Meeting Sheet Update", "TJSM & Co., LLP", "Fincolabs", "GAC-Dogmom", 
  "GAC-TechnoPaints", "Sri global technologies", "Open mind", "Metro Labs", "PSK Group", 
  "Orient spectra", "Choice Mediquip", "Mezbaan", "Bizrights", "Dr. MBV Prasad", 
  "Rajvamshi- Mattress", "Unnadam Avenues", "Ever Green Enterprises", "Delicious", 
  "Ochre Media", "Trully Capital", "Kritsnam", "Studio for eclectic architecture", 
  "Easy Credit India", "Profit Shoe", "Brillica Light nd Fans", "IRUS Tech", 
  "Sridhar Properties", "Trumarx", "Sri Krishna Talpatri", "Krishnasree Project", 
  "BLVRD Apparel", "Orafo", "WIZER Beverages", "Kaushal Jewellers", "BSR Hospital", 
  "Essenn Architecture", "Wingspan Global", "Sia Hospitals", "Instyle Infra", "MRV Mittal", 
  "Dr.Srivanth Ortho", "Sunday Soul Sante", "EMI Bachao", "POCSAYNARSAN", "Coin Bazar", 
  "Axis", "MSD Engg", "Salient Connects", "tansimedinnovatives", "Ask Associates", 
  "GMECO Solutions", "Life Line billing solutions", "Om Sree", "Bass Autism", "Adept", 
  "CoHive Website Design & Development", "BPN", "Act Pressure Cleaning", "BRK Infra Developers", 
  "Vihawk Tech Solutions Private Ltd.", "LSH Dinner", "Pixel", "Associated adv pvt ltd", 
  "BWM", "medilab", "Lorven smart spaces", "makson", "Logictree", "Educational Epiphany", 
  "PavePath Engineering", "Mitra Associates", "Prompt Technical Services", "Nail Art", 
  "Deep mitra", "kothaguda hostel", "MIS Executive", "Ellementry", "Jobmela", 
  "Apsamjwadi Party", "Gouds Business Network", "Business Network Application Development", 
  "Pal Nesto", "D Succed Lerner", "Tatwa Technologies", "Nexen Healthcare", "Linkdin", 
  "The Banyan Foundation", "Sweety Foundation", "Verve Space Exterio", "YPS Infra projects", 
  "Greenspace Housing", "Omnia Steel", "Riddhi Enterprises", "Fenesta", 
  "Jawan security services", "Studio amoli", "Broadminds Infra", "Royal Enfield", 
  "DigiScape Survey", "Jai Siyaram Matrimony", "Aroma", "Freedom Screen", 
  "Manjira Machine Builders", "yellow jersey", "3 Realms Entertainment", "OGL MACH", "MBN", 
  "Teacher Plus", "Efficient Electricals & Electronics", "Inno Bills", "Baking Studios", 
  "Heart touch collections", "Nafa Barter", "Mahi Engineering", "KKmotors", 
  "Data Mation Global", "BIRD Property Management", "BIRD Consulting Services", "Royce Jaeger", 
  "Pioneer Engineer", "wood age", "Team Innovative", "Unicchem", "poddar's stone gallery", 
  "Aakar Granites", "Solomon Capital", "APT and CO LLP", "Big Locker", "PKC laundries", 
  "The Big Lockers", "Overseas Education - Madhu", "Kiats IT Solutions", "agra sweets", 
  "Simply BIZ", "Santhosh laboratory", "CHPL Groups", "Dr. Anish J Anand", "Swiggy", 
  "GA OrgSync RTMAS", "GA OrgSync FSTMS", "Active Cargo", "MCO", "Rootz hair", "Divine Iris", 
  "Sapphire", "Nivi Homes", "Anvitha", "Brov Marketing", "ADB International", 
  "Story Land Library", "Flow Architects", "Intel care", "Corporate Fincon", "Oppenhomes", 
  "American Talkies", "Tanatan India", "Bioneau", "Sanath Accounting", "Disha Traders", 
  "Jagdamba Jewellers", "Fenesta Group", "Disha Traders", "Vijmohan", "HCAH", "Safe Riders", 
  "Rishi Envirotech", "Brewnation", "India Rasoi", "Deccan Prime", "Beats Cardiology", 
  "Excess Interior", "Cloud tech Solutions", "VPR Constructions", "DocTutorials Edutech Pvt. Ltd", 
  "Amazon Van Lines", "Roopa associates", "Unique movers", "Win Win Distribution", "Big Bee", 
  "Lonz360", "Prajay Engineer", "Macrofix", "Open Time", "Pridesoft - LLC", 
  "Simple line Int- Shipping", "Venkat Kitchen", "Dr Rajesh Reddy", "Sankalp", "Mareechi Homes", 
  "Hyderabad Gymkhana", "Concept One Developers", "Iarys herbals", "Softpal Technologies", 
  "Sohom", "SS Enterprises", "CNDU Fabrics", "Sohom", "Wurfel", "SHEagle Trading", 
  "Get A Whiz", "Trinetra Industries", "Panjwani Foods", "SLNS AI driven enterprises", 
  "Artha Group", "Mohd bin Osman Gunna", "SCR Agro Industries", "Bohemian", 
  "Get me Everything", "colossus", "GA - LMS", "Zudio Wafers", "Bkynd Healthcare LLP", 
  "ICPE", "GradArena", "Doctor Laptop Repairs", "GA Grid", "LocoMate", "Yeshura", 
  "Innovate Solutions", "Peace India", "SLRV GROUP", "Podcast", "Sis Aerospace", 
  "Empyrean", "Healing Hastha", "MD Board Prep", "GA Hire Sync", "GA Fields Sync", 
  "Venkatesh Marketing Services", "Business Club Network", "Galaxy Security Services", 
  "Templates / Library Development", "GA Design System", "Minerva Homes", 
  "Nanitransformers", "Cloud Cliff Solutions", "Sleep zzz", "Durosoft", "Crave Kinol Co", 
  "G A Internship Management", "Bharat Next Projects", "UdyogGenie", "Ecommerce- Custom coded", 
  "CreaNovara", "Modest Forever", "AODA training ca", "AKC – Packaging Technology & Research Centre", 
  "Phi Demensions", "Himalaya exports", "Clinic Management Platform", 
  "UFLEX for projects with search option"
];

export const RESOURCE_LIST = [
  "Ameer Basha", "Arjun N", "Daksha", "Dhanush", "Hemachandra", 
  "Mamata", "Rajini", "Renuka", "Venkat", "Nazeer", 
  "Jai Tej", "Aravind", "Vishnu", "Vasantha Lakshmi", "Pramod"
];
